// examples/web-react-vite/src/App.jsx
import { useState, useEffect } from 'react'
import './App.css'
import { initNative, Native } from './native/native.h'

function App() {
  const [message, setMessage] = useState('compiling ...')

  useEffect(() => {
    initNative().then(async () => {
      setMessage(await Native.sample());
    });
  }, []);

  return (
    <>
      <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp; {message}</p>
    </>
  )
}

export default App

// cppjs-samples/cppjs-sample-web-vue-vite/src/App.vue
<script setup>
import { ref } from 'vue'
import { initNative, Native } from './native/native.h'

const message = ref("compiling ...")

initNative().then(async () => {
  message.value = await Native.sample();
});
</script>

<template>
  <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp;  {{message}}</p>
</template>
