// cppjs-samples/cppjs-sample-web-svelte-vite/src/App.svelte
<script>
    import { init } from 'cpp.js';
    import { Native } from './native/native.h';

    let message = 'compiling ...';
    init().then(async () => {
        message = await Native.sample();
    });
</script>

<main>
  <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp; {message}</p>
</main>

// cppjs-samples/cppjs-sample-web-vue-vite/src/App.vue
<script setup>
import { ref } from 'vue'
import { init } from 'cpp.js'
import { Native } from './native/native.h'

const message = ref("compiling ...")

init().then(async () => {
  message.value = await Native.sample();
});
</script>

<template>
  <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp;  {{message}}</p>
</template>
