// samples/cppjs-sample-web-react-vite/src/App.jsx
import { useState, useEffect } from 'react'
import './App.css'
import { initCppJs } from './native/native.h'

function App() {
  const [message, setMessage] = useState('compiling ...')

  useEffect(() => {
    initCppJs().then(({Native}) => {
        setMessage(Native.sample());
    });
  }, []);

  return (
    <>
      <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp; {message}</p>
    </>
  )
}

export default App

// cppjs-samples/cppjs-playground-web-vite/src/App.vue
<script setup>
import { ref } from 'vue'
import { initCppJs, Native } from './native/native.h'

const message = ref("compiling ...")

initCppJs().then(() => {
    message.value = Native.sample();
});
</script>

<template>
  <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp;  {{message}}</p>
</template>
