// cppjs-samples/cppjs-sample-web-vue-vite/src/App.vue
<script setup>
import { ref } from 'vue'
import { initNative, Native } from './native/native.h'

const message = ref("compiling ...")

initNative().then(async () => {
  message.value = await Native.sample();
});
</script>

<template>
  <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp;  {{message}}</p>
</template>

// examples/web-react-rspack/src/App.jsx
import { useState } from 'react';
import { initNative, Native } from './native/native.h';
import './App.css';

function App() {
  const [message, setMessage] = useState("compiling ...");

  initNative().then(async () => {
    setMessage(await Native.sample());
  });

  return (
    <div className="App">
      <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp; {message}</p>
    </div>
  );
}

export default App;
