// cppjs-samples/cppjs-playground-web-vite-multithread/src/App.vue
<script setup>
import { ref } from 'vue'
import { initCppJs, Native } from './native/native.h'

const message = ref("compiling ...")
const threadResult = ref("...")

initCppJs().then((A) => {
    console.log('zzz');
    Native.runOnThread();
    const y = Native.ops_JSPI();
    console.log('zzz2');
    console.log(y);
    y.then(() => {
        console.log('aaa');
        message.value = Native.sample();
    });
    setTimeout(() => {
        threadResult.value = Native.getThreadResult();
    }, 5000);
});
</script>

<template>
  <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp;  {{message}}</p>
  <p>Thread result &nbsp;&nbsp;:&nbsp;&nbsp;  {{threadResult}}</p>
</template>

// cppjs-samples/cppjs-sample-web-svelte-vite-multithread/src/App.svelte
<script>
    import { initCppJs, Native } from './native/native.h';

    let standardResult = $state('compiling ...');
    let threadResult = $state('...');

    initCppJs().then(async () => {
        standardResult = await Native.sample();

        // Run computation on a separate thread
        await Native.runOnThread();

        // Poll for thread result after a short delay
        setTimeout(async () => {
            threadResult = await Native.getThreadResult();
        }, 1000);
    });
</script>

<main>
  <p>Matrix multiplier with c++ &nbsp;&nbsp;=&gt;&nbsp;&nbsp; {standardResult}</p>
  <p>{threadResult}</p>
</main>
